# hermetic/bootstrap.py
# WARNING: THIS FILE IS AUTO-GENERATED BY scripts/build_bootstrap.py. DO NOT EDIT.
from __future__ import annotations
import json
import os
import tempfile
from textwrap import dedent
from typing import Dict, Any
from .errors import BootstrapError

# Minimal bootstrap sitecustomize that installs guards without requiring hermetic package to be importable.
# Encodes guards inline to survive foreign interpreters/venvs.

_SITE_CUSTOMIZE = dedent(
    r'''
    # --- BOOTSTRAP START ---
    import os, sys, json, socket, ssl, subprocess, asyncio, builtins, importlib.machinery as mach, pathlib, time, errno

    class _HPolicy(RuntimeError): pass

    # policy-aware excepthook so bootstrap exits cleanly on guard violations
    _orig_excepthook = sys.excepthook
    def _hermetic_excepthook(exctype, value, tb):
        # Don’t intercept KeyboardInterrupt
        if exctype is KeyboardInterrupt:
            return _orig_excepthook(exctype, value, tb)
        # Our policy exceptions get a clean, consistent exit
        if exctype.__name__ in {"_HPolicy", "PolicyViolation"}:
            try:
                sys.stderr.write(f"hermetic: blocked action: {value}\n")
                sys.stderr.flush()
            finally:
                os._exit(2)  # hard-exit: no teardown that might deadlock
        # otherwise, default behavior
        return _orig_excepthook(exctype, value, tb)

    sys.excepthook = _hermetic_excepthook

    cfg = json.loads(os.environ.pop("HERMETIC_FLAGS_JSON", "{}"))
    trace = bool(cfg.get("trace"))
    def _tr(msg):
        if trace:
            print(f"[hermetic] {msg}", file=sys.stderr, flush=True)

    # --- GUARDS START ---
# --- network ---
    if cfg.get("no_network"):
        _orig_socket = socket.socket
        _orig_socket_type = getattr(socket, "SocketType", None)
        _orig_create_connection = socket.create_connection
        _orig_getaddrinfo = socket.getaddrinfo
        _orig_gethostbyname = socket.gethostbyname
        _orig_gethostbyname_ex = socket.gethostbyname_ex
        _orig_wrap_socket = ssl.SSLContext.wrap_socket
    
        ALLOW_LOCAL = bool(cfg.get("allow_localhost"))
        ALLOW_DOMAINS = set([d.lower() for d in cfg.get("allow_domains", []) if d])
        META = {"169.254.169.254", "metadata.google.internal"}
        LOCAL = {"127.0.0.1","::1","localhost","0.0.0.0"} # nosec
    
        def _host_from(addr):
            try:
                if isinstance(addr, (tuple, list)) and len(addr) >= 1: return str(addr[0])
                return str(addr)
            except Exception: return ""
    
        def _norm_host(host): return (host or "").strip().lower().rstrip(".")
        def _domain_match(host, domain):
            h, d = _norm_host(host), _norm_host(domain)
            return bool(d) and (h == d or h.endswith("." + d))
    
        def _is_net_allowed(host:str)->bool:
            h = _norm_host(host)
            if h in META: return False
            if ALLOW_LOCAL and h in LOCAL: return True
            return any(_domain_match(h, d) for d in ALLOW_DOMAINS)
    
        class GuardedSocket(_orig_socket):
            def connect(self, address):
                host = _host_from(address)
                if _is_net_allowed(host): return super().connect(address)
                _tr(f"blocked socket.connect host={host}"); raise _HPolicy("network disabled")
            def connect_ex(self, address):
                host = _host_from(address)
                if _is_net_allowed(host): return super().connect_ex(address)
                _tr(f"blocked socket.connect_ex host={host}"); return errno.EACCES
            def sendto(self, data, address):
                host = _host_from(address)
                if _is_net_allowed(host): return super().sendto(data, address)
                _tr(f"blocked socket.sendto host={host}"); raise _HPolicy("network disabled")
            if hasattr(_orig_socket, "sendmsg"):
                def sendmsg(self, buffers, ancdata=(), flags=0, address=None):
                    host = _host_from(address)
                    if _is_net_allowed(host): return super().sendmsg(buffers, ancdata, flags, address)
                    _tr(f"blocked socket.sendmsg host={host}"); raise _HPolicy("network disabled")
    
        def _guard_create_connection(addr, *a, **k):
            host = _host_from(addr)
            if _is_net_allowed(host): return _orig_create_connection(addr, *a, **k)
            _tr(f"blocked socket.create_connection host={host}"); raise _HPolicy("network disabled")
    
        def _guard_getaddrinfo(host, *a, **k):
            if _is_net_allowed(str(host)): return _orig_getaddrinfo(host, *a, **k)
            _tr(f"blocked socket.getaddrinfo host={host}"); raise _HPolicy("network disabled")
    
        def _guard_gethostbyname(host, *a, **k):
            if _is_net_allowed(str(host)): return _orig_gethostbyname(host, *a, **k)
            _tr(f"blocked socket.gethostbyname host={host}"); raise _HPolicy("network disabled")
    
        def _guard_gethostbyname_ex(host, *a, **k):
            if _is_net_allowed(str(host)): return _orig_gethostbyname_ex(host, *a, **k)
            _tr(f"blocked socket.gethostbyname_ex host={host}"); raise _HPolicy("network disabled")
    
        def _guard_wrap_socket(self, sock, *a, **k):
            _tr("blocked ssl.wrap_socket"); raise _HPolicy("network disabled")
    
        socket.socket = GuardedSocket
        if _orig_socket_type is not None:
            socket.SocketType = GuardedSocket
        socket.create_connection = _guard_create_connection
        socket.getaddrinfo = _guard_getaddrinfo
        socket.gethostbyname = _guard_gethostbyname
        socket.gethostbyname_ex = _guard_gethostbyname_ex
        ssl.SSLContext.wrap_socket = _guard_wrap_socket
    
    
    # --- subprocess ---
    if cfg.get("no_subprocess"):
        def _deny_exec(*a,**k): _tr("blocked subprocess reason=no-subprocess"); raise _HPolicy("subprocess disabled")
        targets = {
            "subprocess": ("Popen", "run", "call", "check_output"),
            "os": ("system", "execv", "execve", "execl", "execle", "execlp", "execlpe", "execvp", "execvpe", "fork", "forkpty", "spawnl", "spawnle", "spawnlp", "spawnlpe", "spawnv", "spawnve", "spawnvp", "spawnvpe"),
            "asyncio": ("create_subprocess_exec", "create_subprocess_shell"),
            # C-level primitives — POSIX and Windows.
            "_posixsubprocess": ("fork_exec",),
            "_winapi": ("CreateProcess",),
        }
        for mod_name, funcs in targets.items():
            try:
                mod = __import__(mod_name)
                for name in funcs:
                    if hasattr(mod, name):
                        try: setattr(mod, name, _deny_exec)
                        except (AttributeError, TypeError): pass
            except ImportError:
                pass
    
    
    # --- fs readonly ---
    if cfg.get("fs_readonly"):
        ROOT = cfg.get("fs_root")
        _o = {"open": builtins.open, "Popen": pathlib.Path.open, "os.open": os.open}
        def _norm(p):
            try: import os as _os; return _os.path.realpath(p)
            except Exception: return p
        def _within(p, r):
            if not r: return False
            P, R = _norm(p), _norm(r)
            return P==R or P.startswith(R + ("/" if "/" in R else "\\"))
        def _open_guard(f, mode="r", *a, **k):
            path = str(f)
            if any(m in mode for m in ("w","a","x","+")): _tr(f"blocked open write path={path}"); raise _HPolicy("fs readonly")
            if ROOT and not _within(path, ROOT): _tr(f"blocked open read-outside-root path={path}"); raise _HPolicy("read outside root")
            return _o["open"](f, mode, *a, **k)
        WRITE_FLAGS = getattr(os, "O_WRONLY", 2) | getattr(os, "O_RDWR", 4) | getattr(os, "O_APPEND", 8) | getattr(os, "O_CREAT", 1) | getattr(os, "O_TRUNC", 0)
        def os_open_guard(path, flags, *a, **k):
            mode = "r" if not (flags & WRITE_FLAGS) else "w"
            return _open_guard(path, mode, *a, **k)
    
        builtins.open = _open_guard
        pathlib.Path.open = lambda self,*a,**k: _open_guard(str(self), *a, **k)
        os.open = os_open_guard
        def _deny_fs(*a,**k): _tr("blocked fs mutation"); raise _HPolicy("fs mutation disabled")
        for name in ("remove","rename","replace","unlink","rmdir","mkdir","makedirs","chmod","chown","link","symlink","truncate","utime"):
            if hasattr(os, name):
                setattr(os, name, _deny_fs)
        for name in ("chmod","hardlink_to","mkdir","rename","replace","rmdir","symlink_to","touch","unlink"):
            if hasattr(pathlib.Path, name):
                setattr(pathlib.Path, name, _deny_fs)
    
    
    # --- strict imports ---
    if cfg.get("block_native"):
        _origExt = mach.ExtensionFileLoader
        _origImp = builtins.__import__
        _BLOCK_SUBPROC_LIBS = bool(cfg.get("no_subprocess"))
        _DENY = {"ctypes","_ctypes","cffi","_cffi_backend"}
        if _BLOCK_SUBPROC_LIBS:
            _DENY |= {"sh","pexpect","plumbum","sarge","delegator"}
        def _trimp(n): _tr(f"blocked import name={n}")
        def _deny_native_use(name): raise _HPolicy(f"native interface blocked: {name}")
        def _patch_attrs(mod_name, attrs):
            m = sys.modules.get(mod_name)
            if m is None: return
            for a in attrs:
                if hasattr(m, a):
                    try: setattr(m, a, lambda *_a, _n=f"{mod_name}.{a}", **_k: _deny_native_use(_n))
                    except (AttributeError, TypeError): pass
        def _patch_loaded_native_modules():
            _patch_attrs("ctypes", ("CDLL","PyDLL","WinDLL","OleDLL","LibraryLoader","cdll","pydll","windll","oledll"))
            _patch_attrs("ctypes.util", ("find_library","find_msvcrt"))
            _patch_attrs("cffi", ("FFI","dlopen","verify"))
        class GuardedExtLoader(_origExt):
            def create_module(self, spec): _tr(f"blocked native import spec={spec.name}"); raise _HPolicy("native import blocked")
        def guarded_import(name, globals=None, locals=None, fromlist=(), level=0):
            root = name.split(".",1)[0]
            if root in _DENY: _trimp(name); raise _HPolicy("import blocked")
            return _origImp(name, globals, locals, fromlist, level)
        mach.ExtensionFileLoader = GuardedExtLoader
        builtins.__import__ = guarded_import
        _patch_loaded_native_modules()
        try:
            import importlib as _il; _il.invalidate_caches()
        except Exception: pass
    # --- GUARDS END ---
    # --- BOOTSTRAP END ---
    '''
)

def write_sitecustomize(flags: Dict[str, Any]) -> str:
    try:
        d = tempfile.mkdtemp(prefix="hermetic_site_")
        path = os.path.join(d, "sitecustomize.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_SITE_CUSTOMIZE)
        os.environ["HERMETIC_FLAGS_JSON"] = json.dumps(flags)
        return d
    except Exception as e:
        raise BootstrapError(f"failed to write sitecustomize: {e}")
