# hermetic/bootstrap.py
# WARNING: THIS FILE IS AUTO-GENERATED BY scripts/build_bootstrap.py. DO NOT EDIT.
from __future__ import annotations
import json
import os
import tempfile
from textwrap import dedent
from typing import Dict, Any
from .errors import BootstrapError

# Minimal bootstrap sitecustomize that installs guards without requiring hermetic package to be importable.
# Encodes guards inline to survive foreign interpreters/venvs.

_SITE_CUSTOMIZE = dedent(
    r'''
    # --- BOOTSTRAP START ---
    import os, sys, json, socket, ssl, subprocess, asyncio, builtins, importlib.machinery as mach, pathlib, time, errno

    class _HPolicy(RuntimeError): pass

    # policy-aware excepthook so bootstrap exits cleanly on guard violations
    _orig_excepthook = sys.excepthook
    def _hermetic_excepthook(exctype, value, tb):
        # Don’t intercept KeyboardInterrupt
        if exctype is KeyboardInterrupt:
            return _orig_excepthook(exctype, value, tb)
        # Our policy exceptions get a clean, consistent exit
        if exctype.__name__ in {"_HPolicy", "PolicyViolation"}:
            try:
                sys.stderr.write(f"hermetic: blocked action: {value}\n")
                sys.stderr.flush()
            finally:
                os._exit(2)  # hard-exit: no teardown that might deadlock
        # otherwise, default behavior
        return _orig_excepthook(exctype, value, tb)

    sys.excepthook = _hermetic_excepthook

    cfg = json.loads(os.environ.pop("HERMETIC_FLAGS_JSON", "{}"))
    trace = bool(cfg.get("trace"))
    def _tr(msg):
        if trace:
            print(f"[hermetic] {msg}", file=sys.stderr, flush=True)

    # --- GUARDS START ---
# --- environment ---
    if cfg.get("no_environment"):
        class _GuardedEnviron:
            def __init__(self, trace_enabled=False):
                self._trace_enabled = trace_enabled
            def _trace(self, msg):
                if self._trace_enabled:
                    print(f"[hermetic] {msg}", file=sys.stderr, flush=True)
            def _deny_read(self):
                self._trace("blocked environment read")
                raise _HPolicy("environment disabled")
            def _deny_write(self):
                self._trace("blocked environment mutation")
                raise _HPolicy("environment mutation disabled")
            def __getitem__(self, key): self._deny_read()
            def __setitem__(self, key, value): self._deny_write()
            def __delitem__(self, key): self._deny_write()
            def __iter__(self): self._deny_read()
            def __len__(self): self._deny_read()
            def get(self, key, default=None): self._deny_read()
            def copy(self): self._deny_read()
            def items(self): self._deny_read()
            def keys(self): self._deny_read()
            def values(self): self._deny_read()
            def __contains__(self, key): self._deny_read()
            def pop(self, key, default=None): self._deny_write()
            def popitem(self): self._deny_write()
            def clear(self): self._deny_write()
            def setdefault(self, key, default=None): self._deny_write()
            def update(self, *args, **kwargs): self._deny_write()
            def __repr__(self): self._deny_read()
    
        def _deny_env_read(*a, **k):
            _tr("blocked environment read")
            raise _HPolicy("environment disabled")
    
        def _deny_env_write(*a, **k):
            _tr("blocked environment mutation")
            raise _HPolicy("environment mutation disabled")
    
        os.environ = _GuardedEnviron(trace_enabled=trace)
        if hasattr(os, "environb"):
            os.environb = _GuardedEnviron(trace_enabled=trace)
        os.getenv = _deny_env_read
        os.putenv = _deny_env_write
        os.unsetenv = _deny_env_write
    
    
    # --- dynamic code execution ---
    if cfg.get("no_code_exec"):
        def _caller_name(depth=1):
            try:
                frame = sys._getframe(depth + 1)
            except ValueError:
                return ""
            return str(frame.f_globals.get("__name__", ""))
    
        def _compile_is_internal(flags):
            if flags & getattr(__import__("ast"), "PyCF_ONLY_AST", 0):
                return True
            return _caller_name(2).startswith("importlib.")
    
        def _runtime_exec_is_internal():
            return _caller_name(2).startswith("importlib.")
    
        _orig_eval = builtins.eval
        _orig_exec = builtins.exec
        _orig_compile = builtins.compile
        import runpy as _runpy
        _orig_run_module = _runpy.run_module
        _orig_run_path = _runpy.run_path
    
        def _deny_eval(*a, **k):
            _tr("blocked eval")
            raise _HPolicy("dynamic code execution disabled: eval")
    
        def _guard_exec(*a, **k):
            if _runtime_exec_is_internal():
                return _orig_exec(*a, **k)
            _tr("blocked exec")
            raise _HPolicy("dynamic code execution disabled: exec")
    
        def _guard_compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, **kwargs):
            if _compile_is_internal(flags):
                return _orig_compile(source, filename, mode, flags, dont_inherit, optimize, **kwargs)
            _tr("blocked compile")
            raise _HPolicy("dynamic code execution disabled: compile")
    
        def _guard_run_module(*a, **k):
            if _caller_name().startswith("hermetic."):
                return _orig_run_module(*a, **k)
            _tr("blocked runpy.run_module")
            raise _HPolicy("dynamic code execution disabled: run_module")
    
        def _guard_run_path(*a, **k):
            if _caller_name().startswith("hermetic."):
                return _orig_run_path(*a, **k)
            _tr("blocked runpy.run_path")
            raise _HPolicy("dynamic code execution disabled: run_path")
    
        builtins.eval = _deny_eval
        builtins.exec = _guard_exec
        builtins.compile = _guard_compile
        _runpy.run_module = _guard_run_module
        _runpy.run_path = _guard_run_path
    
    
    # --- network ---
    if cfg.get("no_network"):
        _orig_socket = socket.socket
        _orig_socket_type = getattr(socket, "SocketType", None)
        _orig_create_connection = socket.create_connection
        _orig_getaddrinfo = socket.getaddrinfo
        _orig_gethostbyname = socket.gethostbyname
        _orig_gethostbyname_ex = socket.gethostbyname_ex
        _orig_wrap_socket = ssl.SSLContext.wrap_socket
    
        ALLOW_LOCAL = bool(cfg.get("allow_localhost"))
        ALLOW_DOMAINS = set([d.lower() for d in cfg.get("allow_domains", []) if d])
        META = {"169.254.169.254", "metadata.google.internal"}
        LOCAL = {"127.0.0.1","::1","localhost","0.0.0.0"} # nosec
    
        def _host_from(addr):
            try:
                if isinstance(addr, (tuple, list)) and len(addr) >= 1: return str(addr[0])
                return str(addr)
            except Exception: return ""
    
        def _norm_host(host): return (host or "").strip().lower().rstrip(".")
        def _domain_match(host, domain):
            h, d = _norm_host(host), _norm_host(domain)
            return bool(d) and (h == d or h.endswith("." + d))
    
        def _is_net_allowed(host:str)->bool:
            h = _norm_host(host)
            if h in META: return False
            if ALLOW_LOCAL and h in LOCAL: return True
            return any(_domain_match(h, d) for d in ALLOW_DOMAINS)
    
        class GuardedSocket(_orig_socket):
            def connect(self, address):
                host = _host_from(address)
                if _is_net_allowed(host): return super().connect(address)
                _tr(f"blocked socket.connect host={host}"); raise _HPolicy("network disabled")
            def connect_ex(self, address):
                host = _host_from(address)
                if _is_net_allowed(host): return super().connect_ex(address)
                _tr(f"blocked socket.connect_ex host={host}"); return errno.EACCES
            def sendto(self, data, address):
                host = _host_from(address)
                if _is_net_allowed(host): return super().sendto(data, address)
                _tr(f"blocked socket.sendto host={host}"); raise _HPolicy("network disabled")
            if hasattr(_orig_socket, "sendmsg"):
                def sendmsg(self, buffers, ancdata=(), flags=0, address=None):
                    host = _host_from(address)
                    if _is_net_allowed(host): return super().sendmsg(buffers, ancdata, flags, address)
                    _tr(f"blocked socket.sendmsg host={host}"); raise _HPolicy("network disabled")
    
        def _guard_create_connection(addr, *a, **k):
            host = _host_from(addr)
            if _is_net_allowed(host): return _orig_create_connection(addr, *a, **k)
            _tr(f"blocked socket.create_connection host={host}"); raise _HPolicy("network disabled")
    
        def _guard_getaddrinfo(host, *a, **k):
            if _is_net_allowed(str(host)): return _orig_getaddrinfo(host, *a, **k)
            _tr(f"blocked socket.getaddrinfo host={host}"); raise _HPolicy("network disabled")
    
        def _guard_gethostbyname(host, *a, **k):
            if _is_net_allowed(str(host)): return _orig_gethostbyname(host, *a, **k)
            _tr(f"blocked socket.gethostbyname host={host}"); raise _HPolicy("network disabled")
    
        def _guard_gethostbyname_ex(host, *a, **k):
            if _is_net_allowed(str(host)): return _orig_gethostbyname_ex(host, *a, **k)
            _tr(f"blocked socket.gethostbyname_ex host={host}"); raise _HPolicy("network disabled")
    
        def _guard_wrap_socket(self, sock, *a, **k):
            _tr("blocked ssl.wrap_socket"); raise _HPolicy("network disabled")
    
        socket.socket = GuardedSocket
        if _orig_socket_type is not None:
            socket.SocketType = GuardedSocket
        socket.create_connection = _guard_create_connection
        socket.getaddrinfo = _guard_getaddrinfo
        socket.gethostbyname = _guard_gethostbyname
        socket.gethostbyname_ex = _guard_gethostbyname_ex
        ssl.SSLContext.wrap_socket = _guard_wrap_socket
    
    
    # --- subprocess ---
    if cfg.get("no_subprocess"):
        def _deny_exec(*a,**k): _tr("blocked subprocess reason=no-subprocess"); raise _HPolicy("subprocess disabled")
        targets = {
            "subprocess": ("Popen", "run", "call", "check_output"),
            "os": ("system", "execv", "execve", "execl", "execle", "execlp", "execlpe", "execvp", "execvpe", "fork", "forkpty", "spawnl", "spawnle", "spawnlp", "spawnlpe", "spawnv", "spawnve", "spawnvp", "spawnvpe"),
            "asyncio": ("create_subprocess_exec", "create_subprocess_shell"),
            # C-level primitives — POSIX and Windows.
            "_posixsubprocess": ("fork_exec",),
            "_winapi": ("CreateProcess",),
        }
        for mod_name, funcs in targets.items():
            try:
                mod = __import__(mod_name)
                for name in funcs:
                    if hasattr(mod, name):
                        try: setattr(mod, name, _deny_exec)
                        except (AttributeError, TypeError): pass
            except ImportError:
                pass
    
    
    # --- fs readonly ---
    if cfg.get("fs_readonly"):
        ROOT = cfg.get("fs_root")
        _o = {"open": builtins.open, "Popen": pathlib.Path.open, "os.open": os.open}
        def _norm(p):
            try: import os as _os; return _os.path.realpath(p)
            except Exception: return p
        def _within(p, r):
            if not r: return False
            P, R = _norm(p), _norm(r)
            return P==R or P.startswith(R + ("/" if "/" in R else "\\"))
        def _open_guard(f, mode="r", *a, **k):
            path = str(f)
            if any(m in mode for m in ("w","a","x","+")): _tr(f"blocked open write path={path}"); raise _HPolicy("fs readonly")
            if ROOT and not _within(path, ROOT): _tr(f"blocked open read-outside-root path={path}"); raise _HPolicy("read outside root")
            return _o["open"](f, mode, *a, **k)
        WRITE_FLAGS = getattr(os, "O_WRONLY", 2) | getattr(os, "O_RDWR", 4) | getattr(os, "O_APPEND", 8) | getattr(os, "O_CREAT", 1) | getattr(os, "O_TRUNC", 0)
        def os_open_guard(path, flags, *a, **k):
            mode = "r" if not (flags & WRITE_FLAGS) else "w"
            return _open_guard(path, mode, *a, **k)
    
        builtins.open = _open_guard
        pathlib.Path.open = lambda self,*a,**k: _open_guard(str(self), *a, **k)
        os.open = os_open_guard
        def _deny_fs(*a,**k): _tr("blocked fs mutation"); raise _HPolicy("fs mutation disabled")
        for name in ("remove","rename","replace","unlink","rmdir","mkdir","makedirs","chmod","chown","link","symlink","truncate","utime"):
            if hasattr(os, name):
                setattr(os, name, _deny_fs)
        for name in ("chmod","hardlink_to","mkdir","rename","replace","rmdir","symlink_to","touch","unlink"):
            if hasattr(pathlib.Path, name):
                setattr(pathlib.Path, name, _deny_fs)
    
    
    # --- interpreter mutation ---
    if cfg.get("no_interpreter_mutation"):
        import site as _site
    
        class _GuardedList(list):
            def __init__(self, values, label):
                super().__init__(values)
                self._label = label
            def _deny(self):
                _tr(f"blocked {self._label} mutation")
                raise _HPolicy(f"interpreter mutation disabled: {self._label}")
            def append(self, item): self._deny()
            def extend(self, values): self._deny()
            def insert(self, index, item): self._deny()
            def pop(self, index=-1): self._deny()
            def remove(self, item): self._deny()
            def clear(self): self._deny()
            def sort(self, *args, **kwargs): self._deny()
            def reverse(self): self._deny()
            def __setitem__(self, key, value): self._deny()
            def __delitem__(self, key): self._deny()
            def __iadd__(self, other): self._deny()
            def __imul__(self, other): self._deny()
    
        class _GuardedDict(dict):
            def __init__(self, values, label):
                super().__init__(values)
                self._label = label
            def _deny(self):
                _tr(f"blocked {self._label} mutation")
                raise _HPolicy(f"interpreter mutation disabled: {self._label}")
            def __setitem__(self, key, value): self._deny()
            def __delitem__(self, key): self._deny()
            def clear(self): self._deny()
            def pop(self, key, default=None): self._deny()
            def popitem(self): self._deny()
            def setdefault(self, key, default=None): self._deny()
            def update(self, *args, **kwargs): self._deny()
    
        def _deny_chdir(*a, **k):
            _tr("blocked os.chdir")
            raise _HPolicy("interpreter mutation disabled: chdir")
    
        def _deny_fchdir(*a, **k):
            _tr("blocked os.fchdir")
            raise _HPolicy("interpreter mutation disabled: fchdir")
    
        def _deny_addsitedir(*a, **k):
            _tr("blocked site.addsitedir")
            raise _HPolicy("interpreter mutation disabled: addsitedir")
    
        sys.path = _GuardedList(list(sys.path), "sys.path")
        sys.meta_path = _GuardedList(list(sys.meta_path), "sys.meta_path")
        sys.path_hooks = _GuardedList(list(sys.path_hooks), "sys.path_hooks")
        sys.path_importer_cache = _GuardedDict(dict(sys.path_importer_cache), "sys.path_importer_cache")
        os.chdir = _deny_chdir
        if hasattr(os, "fchdir"):
            os.fchdir = _deny_fchdir
        _site.addsitedir = _deny_addsitedir
    
    
    # --- strict imports ---
    if cfg.get("block_native") or cfg.get("deny_imports"):
        _origExt = mach.ExtensionFileLoader
        _origImp = builtins.__import__
        _BLOCK_NATIVE = bool(cfg.get("block_native"))
        _BLOCK_SUBPROC_LIBS = bool(cfg.get("no_subprocess"))
        _DENY = set([n for n in cfg.get("deny_imports", []) if n])
        if _BLOCK_NATIVE:
            _DENY |= {"ctypes","_ctypes","cffi","_cffi_backend"}
        if _BLOCK_NATIVE and _BLOCK_SUBPROC_LIBS:
            _DENY |= {"sh","pexpect","plumbum","sarge","delegator"}
        def _trimp(n): _tr(f"blocked import name={n}")
        def _deny_native_use(name): raise _HPolicy(f"native interface blocked: {name}")
        def _match_import(name, denied):
            root = name.split(".", 1)[0]
            return name == denied or name.startswith(denied + ".") or root == denied
        def _patch_attrs(mod_name, attrs):
            m = sys.modules.get(mod_name)
            if m is None: return
            for a in attrs:
                if hasattr(m, a):
                    try: setattr(m, a, lambda *_a, _n=f"{mod_name}.{a}", **_k: _deny_native_use(_n))
                    except (AttributeError, TypeError): pass
        def _patch_loaded_native_modules():
            _patch_attrs("ctypes", ("CDLL","PyDLL","WinDLL","OleDLL","LibraryLoader","cdll","pydll","windll","oledll"))
            _patch_attrs("ctypes.util", ("find_library","find_msvcrt"))
            _patch_attrs("cffi", ("FFI","dlopen","verify"))
        class GuardedExtLoader(_origExt):
            def create_module(self, spec): _tr(f"blocked native import spec={spec.name}"); raise _HPolicy("native import blocked")
        def guarded_import(name, globals=None, locals=None, fromlist=(), level=0):
            if any(_match_import(name, denied) for denied in _DENY): _trimp(name); raise _HPolicy("import blocked")
            return _origImp(name, globals, locals, fromlist, level)
        if _BLOCK_NATIVE:
            mach.ExtensionFileLoader = GuardedExtLoader
        builtins.__import__ = guarded_import
        if _BLOCK_NATIVE:
            _patch_loaded_native_modules()
            try:
                import importlib as _il; _il.invalidate_caches()
            except Exception: pass
    # --- GUARDS END ---
    # --- BOOTSTRAP END ---
    '''
)

def write_sitecustomize(flags: Dict[str, Any]) -> str:
    try:
        d = tempfile.mkdtemp(prefix="hermetic_site_")
        path = os.path.join(d, "sitecustomize.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_SITE_CUSTOMIZE)
        os.environ["HERMETIC_FLAGS_JSON"] = json.dumps(flags)
        return d
    except Exception as e:
        raise BootstrapError(f"failed to write sitecustomize: {e}")
